# Generated by Django 4.1.3 on 2022-11-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
